name: Docker Image CI
#
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag shubhamdixit863/eduyogi-frontend:latest
      - name: Login To Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push the Image to Docker Hub
        run: docker push shubhamdixit863/eduyogi-frontend:latest

  deploy:
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Set up kubectl with your DigitalOcean Kubernetes cluster
      - name: Set up kubectl
        uses: matootie/dokube@v1.4.0
        with:
          personalAccessToken: ${{ secrets.DIGITALOCEAN_TOKEN }}
          clusterName: k8s-1-29-1-do-0-nyc1-1713686144974
      # Run kubectl commands to deploy your application
      - name: Deploy Application
        run: |
          kubectl delete deployment nextjs-deployment || true
          kubectl apply -f k8_frontend.yaml
